name: timeapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.6.18
  http: ^1.1.2
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/login.png"
