#############################################
GET http://192.168.18.35:4912/perfil/producto
  ?perfil_id=1
  &producto_id=53

#############################################
GET http://192.168.18.35:4912/perfil/resume
  ?perfil_id=1

#############################################
GET http://192.168.18.35:4912/perfil/productos
  ?perfil_id=1